---
version: '3.8'

services:
  runner:
    image: github-runner:latest
    build:
      context: .
      args:
        RUNNER_VERSION: '2.305.0'
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GH_OWNER: ${GH_OWNER}
      GH_REPOSITORY: ${GH_REPOSITORY}
    privileged: true
    devices:
      - "/dev/kvm:/dev/kvm"
